### ISSUE TITLE
Crashes in Max 7.0.2

### ISSUE THREAD

**Issue by tap** [cmuartfab/ml-lib#114]
I have received reports that these externs (e.g. ml.adaboost) crash in Max 7.0.2 (e.g. try to open the help patcher).  I am able to reproduce the crashing, but the backtrace is different every time, suggesting that this object is corrupting memory.

One the best tools for narrowing that down is using Enable Guard Malloc in Xcode, but that really is only effective in Max in 64-bit.  These objects not compiled for 64-bits.

I cloned the git repository, but the project doesn't build.  I fixed the paths but then there are still other problems.  For example, error() and post() are Max SDK symbols which nowadays are actually macros and the conflicting symbol use here is a problem.

Trying to divine from the source code where memory might be corrupting is a challenge.  The version of flext being used is apparently 3 or 4 years old.  But it's hard to diagnose parts of this as those in the repository as compiled static libs. Perhaps they are then linking to a version of the c++ standard library that is incompatible with what Max links to and the symbols conflict? But here I am grasping at straws since it is hard to tell from the project what is going on precisely.

I bring up flext because the call stack I've seen a couple of times includes a call to a delete operator that somehow worms its way to a sysmem_freeptr call.  I can see in the flsupport.h that operators new and delete are overloaded but nowhere do I see them using sysmem calls. Maybe the stack is corrupted, or maybe its using sysmem internally in those static libs, or maybe there is a runtime symbol conflict somewhere, or ???

Let me know if you need any help. I'm happy to help if I can (though I'll need to be able to build using current Apple dev tools and Max SDK to do so). Cheers!

**Comment by jamiebullock** [comment]
Thanks Tim. First up, I'm curious as to where you heard the reports as it would be good to follow up there directly.

These externals haven't been tested (by me at least) in Max 7. I think @batchku tested them in Max 7 and also had issues, and it is on my TODO list to investigate this. I've now updated the [README](https://github.com/cmuartfab/ml-lib/blob/master/README.md) with this information.

I was aware of the Memory Diagnostics tools in Xcode, but thanks for pointing that out!

I think your ideas about the objects crashing in Flext are plausible. We've had weird issues with Flext previously, which have been resolved, but there is a lot of "voodoo" going on in there for sure, which could definitely be a source of the kinds of issues we're seeing.

NOTE: the stated FLEXT version in flext.h is actually incorrect. The current ml-lib is built against Flext svn revision 3786 (November 2013). There have only been build system changes in FLEXT trunk since then.

**Comment by tap** [comment]
The difference in version between FLEXT header and libs might explain what I've seen in a number of the crashes I was looking at -- where it looked like FLEXT was trying to free memory with sysmem_freeptr() that had been alloced with malloc().  Not certain that's what was happening, but there is a flavor of that present.

Cheers!

**Comment by jamiebullock** [comment]
Fixed in ae5ebfbfae21ae6418fbf4fdc3c6918cb6eeb317
