### ISSUE TITLE
ml.dtw: Unable to Map Input 

### ISSUE THREAD

**Issue by JCurtisRMIT** [cmuartfab/ml-lib#133]
Attempting to follow the helpfile, receiving "error ml.dtw: unable to map input"

Training phase needs much better clarification in the helpfile:

Procedurally, where exactly should the line objects be triggered? 
How does the 'Test' subpatch relate to the main patch? 
When are these operations intended to be triggered to train correctly?

Also:
send objects are labeled [s mlp] instead of [s dtw]

**Comment by JCurtisRMIT** [comment]
@jamiebullock

**Comment by JCurtisRMIT** [comment]
Finally, how do you suggest training multiple examples for gesture recognition within ml.dtw?

If you can provide me clear examples on how to get this running correctly I'd be glad to create a clear helpfile for you!

**Comment by jamiebullock** [comment]
Hi @JCurtisRMIT, sorry for the slow reply!

This issue is now duplicated by a more recent issue (#145) 

The helpful is basically misleading. Record needs to be toggled on / off for each training example. Additionally, it should be used for segmentation during `map`. So the typical sequence is:

record 1
add <class 1> ...
record 0
record 1
add <class 2> ...
record 0

etc

train

record 1
map <observations 1> 
record 0
record 1
map <observations 2>
record 0

etc

I explain this in more detail in #145. In an upcoming release the helpfile will be improved. Does this answer the question?
